server:
  port: 29001
spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hdsx?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
# dubbo
dubbo:
  application:
    id: user-service
    name: user-service  #应用名称
    owner: lcc      #应用所属者
    organization: hdsx   #应用所属组织
  registry:
    id: zookeeper-registry #注册中心id
    protocol: zookeeper    #注册中心协议
    address: zookeeper://127.0.0.1:2181 #注册中心地址
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo   #协议名称
    port: -1   #协议端口
    accesslog: dubbo-access.log #协议访问log
  provider:
    retries: 0    #重试次数
    timeout: 3000 #超时时间
    UserService:
      version: 1.0.0
#  monitor:
#    protocol: registry # 注册监控中心
# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: user-producer-spu-collection-group
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  config-location: classpath:mybatis-config.xml

