spring:
  application:
    name: dubbo-registry-nacos-consumer-sample
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      metric:
        charset: UTF-8
      eager: false
server:
  port: 18081
demo:
  service:
    version: 1.0.0
nacos:
  host: 127.0.0.1
  port: 8848
dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}
java.net.preferIPv4Stack: true
csp.sentinel.api.port: 8083
project.name: consumer-service1
csp.sentinel.dashboard.server: 127.0.0.1:8080


